### ISSUE TITLE
Function missing problem

### ISSUE THREAD

**Issue by qishengjie9** [jbonaiuto/laminar_sim#1]
hello，jbonaiuto
Recently I tried to reproduce your article through your code with open data. But when plotting the results, I found a function missing. In function "compute_roi_t_stat", you used a function called "map_pial_to_white". But I can't find this function. Could you please check this problem for me
Best regards!

**Comment by jbonaiuto** [comment]
This function is in an older version of MEGsurfer:
https://github.com/jbonaiuto/MEGsurfer/tree/704592573dd3597ceaed0a11ffca3b8c09d22d33
